### ISSUE TITLE
Missing mvtec module for runner.py to import

### ISSUE THREAD

**Issue by GreatScherzo** [taikiinoue45/PaDiM#4]
There seems to be a missing relative python module for the runner to import. 
https://github.com/taikiinoue45/PaDiM/blob/main/padim/runner/runner.py#L7-L9

Thank you for taking your time in reading this issue.

**Comment by taikiinoue45** [comment]
I just updated README.md. Could you try [5. Usage](https://github.com/taikiinoue45/PaDiM/blob/main/README.md#5-usage) part again. 

`mvtec` module is prepared as a python library. You can install `mvtec` with the following command. However, docker image `taikiinoue45/mvtec:padim` already installed `mvtec`, and you don't need to download and install them.

```
git clone https://github.com/taikiinoue45/mvtec-utils.git
cd mvtec-utils
python -m pip install .
```

**Comment by GreatScherzo** [comment]
Ah, the mvtec module is in another repo.

The code ran without a problem, thank you!
